### ISSUE TITLE
Electro - Elementor - Requirements

### ISSUE THREAD

**Issue by jameer1612** [madrasthemes/mas-elementor#60]
- [x] Button icon color and alignment controls
- [x] Product add to cart icon

**Comment by YahyaTec** [comment]
- [ ] Product Price Widget

**Comment by YahyaTec** [comment]
- [ ] Progress Bar Widget

![image](https://github.com/madrasthemes/mas-elementor/assets/86230293/b79d4329-23a2-4e3a-9c21-caec6c6fabf6)

**Comment by YahyaTec** [comment]
- [ ] add carousel pagination to achieve this

![image](https://github.com/madrasthemes/mas-elementor/assets/86230293/1b985129-2c86-4c0e-a83e-f212f4008495)

**Comment by YahyaTec** [comment]
- [ ] Product Categories

![image](https://github.com/madrasthemes/mas-elementor/assets/86230293/c173f948-1ebf-409d-89e0-4a4d83b44527)

**Comment by jameer1612** [comment]
- [ ] Post widget height control
- [ ] Multipurpose Text Gradient color
- [ ] price widget margin <p>

**Comment by jameer1612** [comment]
-[ ] MAS Nav Tabs Position Responsive Control Need

**Comment by jameer1612** [comment]
- [ ] Product categories Divider control
- [ ] Hover Typography
- [ ] ![image](https://github.com/madrasthemes/mas-elementor/assets/80022978/bab2cc42-7e71-41bd-a021-d7bc366c5793)

**Comment by jameer1612** [comment]
![image](https://github.com/madrasthemes/mas-elementor/assets/80022978/8042c408-0e22-4a3f-bf92-59af33ec1cdd)

- [ ] Need control for Position Show count result

**Comment by jameer1612** [comment]
- [ ] Home v12 need Category skin
- [ ] 
![image](https://github.com/madrasthemes/mas-elementor/assets/80022978/ffe720b4-aa5a-4770-85bd-eeb192814510)

**Comment by jameer1612** [comment]
- [ ] Brands Need Home v12 
- [ ] ![image](https://github.com/madrasthemes/mas-elementor/assets/80022978/03afd7ab-4b19-4424-a717-dd1a8866f6fd)

**Comment by jameer1612** [comment]
- [ ] Image widget width - 100 control need

**Comment by jameer1612** [comment]
- [ ] Recently Viewed Products

**Comment by jameer1612** [comment]
- [ ] Accordion Control needs
   - [ ] Icon Background
   - [ ] Icon Border
   - [ ] Hover typography

**Comment by jameer1612** [comment]
![image](https://github.com/madrasthemes/mas-elementor/assets/80022978/6b525162-7223-4570-b1bb-fba33e774b0f)

**Comment by jameer1612** [comment]
- [ ] Blog Post Format issues in loop
- [ ] Blog post pagination spacing controls
